### ISSUE TITLE
Investigate if Fandango API payments still work

### ISSUE THREAD

**Issue by rohenp** [codepath-movie-app/trailer-trash#101]

**Comment by priyam** [comment]
The affiliate program is mostly about getting links for browsers. We can get a link to a particular showtime  which then takes user to fandango website to complete the purchase experience. It will look something like this:
![screen shot 2015-04-05 at 12 10 00 am](https://cloud.githubusercontent.com/assets/769269/6996114/6f94a42c-db28-11e4-8add-f7e1d9ab3b7f.png)

**Comment by rohenp** [comment]
How would we associate the link with the movie time? This looks extremely
doable.


Rohen Peterson

**Comment by priyam** [comment]
this wont work due to the session issue
