### ISSUE TITLE
enable back button navigation on planning fragments

### ISSUE THREAD

**Issue by priyam** [codepath-movie-app/trailer-trash#64]

**Comment by rohenp** [comment]
Added the toolbar in the activity since I was doing it for a bunch of others. You might need to clean up some data if you create a UserMovie, UserGroup, or Group before the finish call.

**Comment by priyam** [comment]
leaving the toolbar button navigation intact to go back to activity since thats hierarchically up in our flow, based on http://developer.android.com/design/patterns/navigation.html
